export const ADD_TRACK = "ADD_TRACK";
export const DELETE_TRACK = "DELETE_TRACK";

export const GET_TRACKS = "GET_TRACKS";

export const SEARCH_TRACKS_START = "SEARCH_TRACKS_START";
export const SEARCH_TRACKS = "SEARCH_TRACKS";
export const SEARCH_TRACKS_SUCCESS = "SEARCH_TRACKS_SUCCESS";
export const SEARCH_TRACKS_FAIL = "SEARCH_TRACKS_FAIL";

export const SAVE_PLAYLIST_START = "SAVE_PLAYLIST_START";
export const SAVE_PLAYLIST = "SAVE_PLAYLIST";
export const SAVE_PLAYLIST_SUCCESS = "SAVE_PLAYLIST_SUCCESS";
export const SAVE_PLAYLIST_FAIL = "SAVE_PLAYLIST_FAIL";

export const AUTH_START = "AUTH_START";
export const AUTH_USER = "AUTH_USER";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_REDIRECT = "AUTH_REDIRECT";

export const AUTH_CHECK_STATE = "AUTH_CHECK_STATE";
export const AUTH_CHECK_TIMEOUT = "AUTH_CHECK_TIMEOUT";
