export const ADD_TRACK = "ADD_TRACK";
export const DELETE_TRACK = "DELETE_TRACK";
export const SET_TRACKS = "SET_TRACKS";

export const SEARCH_TRACKS_START = "SEARCH_TRACKS_START";
export const SEARCH_TRACKS = "SEARCH_TRACKS";
export const SEARCH_TRACKS_SUCCESS = "SEARCH_TRACKS_SUCCESS";
export const SEARCH_TRACKS_FAIL = "SEARCH_TRACKS_FAIL";

export const SAVE_PLAYLIST_START = "SAVE_PLAYLIST_START";
export const SAVE_PLAYLIST = "SAVE_PLAYLIST";
export const SAVE_PLAYLIST_SUCCESS = "SAVE_PLAYLIST_SUCCESS";
export const SAVE_PLAYLIST_FAIL = "SAVE_PLAYLIST_FAIL";
export const SUCCESS_CONFIRM = "SUCCESS_CONFIRM";

export const EDIT_PLAYLIST_START = "EDIT_PLAYLIST_START";
export const EDIT_PLAYLIST = "EDIT_PLAYLIST";
export const EDIT_PLAYLIST_SUCCESS = "EDIT_PLAYLIST_SUCCESS";
export const EDIT_PLAYLIST_FAIL = "EDIT_PLAYLIST_FAIL";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const SET_AUTH_REDIRECT_URL = "SET_AUTH_REDIRECT_URL";
export const AUTH_CHECK_STATE = "AUTH_CHECK_STATE";
export const AUTH_CHECK_TIMEOUT = "AUTH_CHECK_TIMEOUT";

export const PLAY_TRACK_STATE_UPDATE = "PLAY_TRACK_STATE_UPDATE";
export const PLAY_TRACK_START = "PLAY_TRACK_START";
export const PLAY_TRACK_PAUSE = "PLAY_TRACK_PAUSE";
export const PLAY_TRACK_END = "PLAY_TRACK_END";
export const PLAY_TRACK_FAIL = "PLAY_TRACK_FAIL";

export const FETCH_PLAYLISTS_START = "FETCH_PLAYLISTS_START";
export const FETCH_PLAYLISTS = "FETCH_PLAYLISTS";
export const FETCH_PLAYLISTS_SUCCESS = "FETCH_PLAYLISTS_SUCCESS";
export const FETCH_PLAYLISTS_FAIL = "FETCH_PLAYLISTS_FAIL";
export const CLEAR_PLAYLIST = "CLEAR_PLAYLIST";
export const SET_REDIRECT = "SET_REDIRECT";

export const FETCH_TRACKS_START = "FETCH_TRACKS_START";
export const FETCH_TRACKS = "FETCH_TRACKS";
export const FETCH_TRACKS_SUCCESS = "FETCH_TRACKS_SUCCESS";
export const FETCH_TRACKS_FAIL = "FETCH_TRACKS_FAIL";

export const DELETE_TRACKS_START = "DELETE_TRACKS_START";
export const DELETE_TRACKS = "DELETE_TRACKS";
export const DELETE_TRACKS_SUCCESS = "DELETE_TRACKS_SUCCESS";
export const DELETE_TRACKS_FAIL = "DELETE_TRACKS_FAIL";
